### ISSUE TITLE
Add Readme

### ISSUE THREAD

**Issue by deadbirdi** [sneakycrow/cribot#1]
Add readme including installation instructions

**Comment by j-tesla** [comment]
@sneakycrow I'd like to work on it.

**Comment by deadbirdi** [comment]
@j-tesla Awesome! The instructions are fairly basic:

1. Install dependencies off of requirements.txt
2. Create an environment variable called `DISCORD_TOKEN` that contains your bot token from Discord.
3. Run `main.py`

If you could add the shell commands for each of those steps as well, that'd be rad! Thank you!

**Comment by deadbirdi** [comment]
You really did great! Above and beyond! Thank you !
